baseURL: "https://luxury-pony-876c53.netlify.app"
languageCode: en-us
title: Rustam Lukmanov
theme: PaperMod

#trlalala
params:
  enableEmoji: true
  profileMode:
        enabled: false
        title: "Hi!" # optional default will be site title
        subtitle: "This is subtitle"
        imageUrl: "images/Profile.jpg" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 350 # custom size
        imageHeight: 250 # custom size
        buttons:
#            - name: Archive
#            url: "/archive"
#            - name: Github
#            url: "https://github.com/"
  homeInfoParams:
    Title: "Hi! :wave: Welcome to my page!"
    Content: "Welcome to my blog and info page! You will a lot of cool information on my page.
    sdlkfjas;ldkjf;alskdjf
    fa;sldkjf;lkasdjf;laks
    ;lkasdjf;lkasjd"
  socialICons:
      - name: facebook
        url: "https://www.facebook.com/rustam.lukmanov.73"
      - name: LinkedIn
        url: "https://www.linkedin.com/in/rustam-lukmanov-604695100/"
  cover: 
#  image: "images/Profile.jpg"
    linkFullImages: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ##ShowShareButtons: true
menu:
  main:
  - identifier: categories
    name: Categories
    url: /categories/
    weight: 20
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 30
  - idneitfier: archives
    name: Archives
    url: /archives/
    weight: 40 
    
  - identifier: Publications
    name: Publications
    url: /publications/
    weight: 50

# - identifier: CV
#    name: CV
#    url: /CV/
#    weight: 10